packages:
  - 'packages/*'
publicHoistPattern:
  - eslint
  - prettier
minimumReleaseAgeExclude:
  - '@siberiacancode/reactuse'
allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  sharp: true
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
