packages:
  - 'packages/*'
publicHoistPattern:
  - eslint
  - prettier
minimumReleaseAgeExclude:
  - '@siberiacancode/reactuse'
  - '@siberiacancode/eslint'
allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  sharp: true
