import { promises as fs } from 'fs';
import path from 'path';
import { rimraf } from 'rimraf';

async function buildExamplesIndex() {
  const cwd = process.cwd();
  const examplesDir = path.join(cwd, '../../packages/core/src/hooks');

  await fs.access(examplesDir);
  console.log('📋 Generating examples/__index__.tsx...');

  const allEntries = await fs.readdir(examplesDir, { withFileTypes: true });

  const folders = allEntries
    .filter((entry) => !entry.isFile())
    .map((entry) => entry.name)
    .sort();

  const files = await Promise.all(
    Array.from(folders).map(async (folder) => {
      const allEntries = await fs.readdir(path.join(examplesDir, folder), { withFileTypes: true });

      const files = allEntries
        .filter((entry) => entry.isFile() && entry.name.endsWith('.demo.tsx'))
        .map((entry) => entry.name)
        .sort();

      return { name: folder, demo: files[0] };
    })
  );

  console.log(`   Found ${files.length} demos`);

  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-examples.ts
// Do not edit this file directly.
import * as React from "react"

export const ExamplesIndex: Record<string, Record<string, any>> = {`;

  console.log('files', files);

  for (const file of files) {
    const name = file.name.replace(/\.tsx$/, '');

    index += `
      "${name}": {
        name: "${name}",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/${file.name}/${file.demo}")
          return mod
        }),
      },
  `;
  }

  index += '}';

  const indexPath = path.join(cwd, '__index__.tsx');
  await rimraf(indexPath);
  await fs.writeFile(indexPath, index);
  console.log(`\n✅ Generated examples/__index__.tsx`);
}

buildExamplesIndex().catch(console.error);
