// @ts-nocheck
// This file is autogenerated by scripts/build-examples.ts
// Do not edit this file directly.
import * as React from "react"

export const ExamplesIndex: Record<string, Record<string, any>> = {
      "useActiveElement": {
        name: "useActiveElement",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useActiveElement/useActiveElement.demo.tsx")
          return mod
        }),
      },
  
      "useAsync": {
        name: "useAsync",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useAsync/useAsync.demo.tsx")
          return mod
        }),
      },
  
      "useAsyncEffect": {
        name: "useAsyncEffect",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useAsyncEffect/useAsyncEffect.demo.tsx")
          return mod
        }),
      },
  
      "useAudio": {
        name: "useAudio",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useAudio/useAudio.demo.tsx")
          return mod
        }),
      },
  
      "useAutoScroll": {
        name: "useAutoScroll",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useAutoScroll/useAutoScroll.demo.tsx")
          return mod
        }),
      },
  
      "useBatchedCallback": {
        name: "useBatchedCallback",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBatchedCallback/useBatchedCallback.demo.tsx")
          return mod
        }),
      },
  
      "useBattery": {
        name: "useBattery",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBattery/useBattery.demo.tsx")
          return mod
        }),
      },
  
      "useBluetooth": {
        name: "useBluetooth",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBluetooth/useBluetooth.demo.tsx")
          return mod
        }),
      },
  
      "useBoolean": {
        name: "useBoolean",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBoolean/useBoolean.demo.tsx")
          return mod
        }),
      },
  
      "useBreakpoints": {
        name: "useBreakpoints",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBreakpoints/useBreakpoints.demo.tsx")
          return mod
        }),
      },
  
      "useBroadcastChannel": {
        name: "useBroadcastChannel",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBroadcastChannel/useBroadcastChannel.demo.tsx")
          return mod
        }),
      },
  
      "useBrowserLanguage": {
        name: "useBrowserLanguage",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useBrowserLanguage/useBrowserLanguage.demo.tsx")
          return mod
        }),
      },
  
      "useClickOutside": {
        name: "useClickOutside",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useClickOutside/useClickOutside.demo.tsx")
          return mod
        }),
      },
  
      "useClipboard": {
        name: "useClipboard",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useClipboard/useClipboard.demo.tsx")
          return mod
        }),
      },
  
      "useConst": {
        name: "useConst",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useConst/useConst.demo.tsx")
          return mod
        }),
      },
  
      "useControllableState": {
        name: "useControllableState",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useControllableState/useControllableState.demo.tsx")
          return mod
        }),
      },
  
      "useCookie": {
        name: "useCookie",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useCookie/useCookie.demo.tsx")
          return mod
        }),
      },
  
      "useCookies": {
        name: "useCookies",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useCookies/useCookies.demo.tsx")
          return mod
        }),
      },
  
      "useCopy": {
        name: "useCopy",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useCopy/useCopy.demo.tsx")
          return mod
        }),
      },
  
      "useCounter": {
        name: "useCounter",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useCounter/useCounter.demo.tsx")
          return mod
        }),
      },
  
      "useCssVar": {
        name: "useCssVar",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useCssVar/useCssVar.demo.tsx")
          return mod
        }),
      },
  
      "useDebounceCallback": {
        name: "useDebounceCallback",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDebounceCallback/useDebounceCallback.demo.tsx")
          return mod
        }),
      },
  
      "useDebounceEffect": {
        name: "useDebounceEffect",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDebounceEffect/useDebounceEffect.demo.tsx")
          return mod
        }),
      },
  
      "useDebounceState": {
        name: "useDebounceState",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDebounceState/useDebounceState.demo.tsx")
          return mod
        }),
      },
  
      "useDebounceValue": {
        name: "useDebounceValue",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDebounceValue/useDebounceValue.demo.tsx")
          return mod
        }),
      },
  
      "useDefault": {
        name: "useDefault",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDefault/useDefault.demo.tsx")
          return mod
        }),
      },
  
      "useDeviceMotion": {
        name: "useDeviceMotion",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDeviceMotion/useDeviceMotion.demo.tsx")
          return mod
        }),
      },
  
      "useDeviceOrientation": {
        name: "useDeviceOrientation",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDeviceOrientation/useDeviceOrientation.demo.tsx")
          return mod
        }),
      },
  
      "useDevicePixelRatio": {
        name: "useDevicePixelRatio",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDevicePixelRatio/useDevicePixelRatio.demo.tsx")
          return mod
        }),
      },
  
      "useDidUpdate": {
        name: "useDidUpdate",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDidUpdate/useDidUpdate.demo.tsx")
          return mod
        }),
      },
  
      "useDisclosure": {
        name: "useDisclosure",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDisclosure/useDisclosure.demo.tsx")
          return mod
        }),
      },
  
      "useDisplayMedia": {
        name: "useDisplayMedia",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDisplayMedia/useDisplayMedia.demo.tsx")
          return mod
        }),
      },
  
      "useDocumentEvent": {
        name: "useDocumentEvent",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDocumentEvent/useDocumentEvent.demo.tsx")
          return mod
        }),
      },
  
      "useDocumentTitle": {
        name: "useDocumentTitle",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDocumentTitle/useDocumentTitle.demo.tsx")
          return mod
        }),
      },
  
      "useDocumentVisibility": {
        name: "useDocumentVisibility",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDocumentVisibility/useDocumentVisibility.demo.tsx")
          return mod
        }),
      },
  
      "useDoubleClick": {
        name: "useDoubleClick",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDoubleClick/useDoubleClick.demo.tsx")
          return mod
        }),
      },
  
      "useDropZone": {
        name: "useDropZone",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useDropZone/useDropZone.demo.tsx")
          return mod
        }),
      },
  
      "useEvent": {
        name: "useEvent",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useEvent/useEvent.demo.tsx")
          return mod
        }),
      },
  
      "useEventListener": {
        name: "useEventListener",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useEventListener/useEventListener.demo.tsx")
          return mod
        }),
      },
  
      "useEventSource": {
        name: "useEventSource",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useEventSource/useEventSource.demo.tsx")
          return mod
        }),
      },
  
      "useEyeDropper": {
        name: "useEyeDropper",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useEyeDropper/useEyeDropper.demo.tsx")
          return mod
        }),
      },
  
      "useFavicon": {
        name: "useFavicon",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFavicon/useFavicon.demo.tsx")
          return mod
        }),
      },
  
      "useField": {
        name: "useField",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useField/useField.demo.tsx")
          return mod
        }),
      },
  
      "useFileDialog": {
        name: "useFileDialog",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFileDialog/useFileDialog.demo.tsx")
          return mod
        }),
      },
  
      "useFocus": {
        name: "useFocus",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFocus/useFocus.demo.tsx")
          return mod
        }),
      },
  
      "useFocusTrap": {
        name: "useFocusTrap",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFocusTrap/useFocusTrap.demo.tsx")
          return mod
        }),
      },
  
      "useFps": {
        name: "useFps",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFps/useFps.demo.tsx")
          return mod
        }),
      },
  
      "useFul": {
        name: "useFul",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFul/useFul.demo.tsx")
          return mod
        }),
      },
  
      "useFullscreen": {
        name: "useFullscreen",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useFullscreen/useFullscreen.demo.tsx")
          return mod
        }),
      },
  
      "useGamepad": {
        name: "useGamepad",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useGamepad/useGamepad.demo.tsx")
          return mod
        }),
      },
  
      "useGeolocation": {
        name: "useGeolocation",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useGeolocation/useGeolocation.demo.tsx")
          return mod
        }),
      },
  
      "useHash": {
        name: "useHash",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useHash/useHash.demo.tsx")
          return mod
        }),
      },
  
      "useHotkeys": {
        name: "useHotkeys",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useHotkeys/useHotkeys.demo.tsx")
          return mod
        }),
      },
  
      "useHover": {
        name: "useHover",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useHover/useHover.demo.tsx")
          return mod
        }),
      },
  
      "useIdle": {
        name: "useIdle",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useIdle/useIdle.demo.tsx")
          return mod
        }),
      },
  
      "useImage": {
        name: "useImage",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useImage/useImage.demo.tsx")
          return mod
        }),
      },
  
      "useInfiniteScroll": {
        name: "useInfiniteScroll",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useInfiniteScroll/useInfiniteScroll.demo.tsx")
          return mod
        }),
      },
  
      "useIntersectionObserver": {
        name: "useIntersectionObserver",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useIntersectionObserver/useIntersectionObserver.demo.tsx")
          return mod
        }),
      },
  
      "useInterval": {
        name: "useInterval",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useInterval/useInterval.demo.tsx")
          return mod
        }),
      },
  
      "useIsFirstRender": {
        name: "useIsFirstRender",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useIsFirstRender/useIsFirstRender.demo.tsx")
          return mod
        }),
      },
  
      "useIsomorphicLayoutEffect": {
        name: "useIsomorphicLayoutEffect",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useIsomorphicLayoutEffect/useIsomorphicLayoutEffect.demo.tsx")
          return mod
        }),
      },
  
      "useKeyPress": {
        name: "useKeyPress",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useKeyPress/useKeyPress.demo.tsx")
          return mod
        }),
      },
  
      "useKeyPressEvent": {
        name: "useKeyPressEvent",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useKeyPressEvent/useKeyPressEvent.demo.tsx")
          return mod
        }),
      },
  
      "useKeyboard": {
        name: "useKeyboard",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useKeyboard/useKeyboard.demo.tsx")
          return mod
        }),
      },
  
      "useKeysPressed": {
        name: "useKeysPressed",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useKeysPressed/useKeysPressed.demo.tsx")
          return mod
        }),
      },
  
      "useLastChanged": {
        name: "useLastChanged",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLastChanged/useLastChanged.demo.tsx")
          return mod
        }),
      },
  
      "useLatest": {
        name: "useLatest",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLatest/useLatest.demo.tsx")
          return mod
        }),
      },
  
      "useLess": {
        name: "useLess",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLess/useLess.demo.tsx")
          return mod
        }),
      },
  
      "useList": {
        name: "useList",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useList/useList.demo.tsx")
          return mod
        }),
      },
  
      "useLocalStorage": {
        name: "useLocalStorage",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLocalStorage/useLocalStorage.demo.tsx")
          return mod
        }),
      },
  
      "useLockCallback": {
        name: "useLockCallback",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLockCallback/useLockCallback.demo.tsx")
          return mod
        }),
      },
  
      "useLockScroll": {
        name: "useLockScroll",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLockScroll/useLockScroll.demo.tsx")
          return mod
        }),
      },
  
      "useLogger": {
        name: "useLogger",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLogger/useLogger.demo.tsx")
          return mod
        }),
      },
  
      "useLongPress": {
        name: "useLongPress",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useLongPress/useLongPress.demo.tsx")
          return mod
        }),
      },
  
      "useMap": {
        name: "useMap",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMap/useMap.demo.tsx")
          return mod
        }),
      },
  
      "useMeasure": {
        name: "useMeasure",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMeasure/useMeasure.demo.tsx")
          return mod
        }),
      },
  
      "useMediaControls": {
        name: "useMediaControls",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMediaControls/useMediaControls.demo.tsx")
          return mod
        }),
      },
  
      "useMediaQuery": {
        name: "useMediaQuery",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMediaQuery/useMediaQuery.demo.tsx")
          return mod
        }),
      },
  
      "useMemory": {
        name: "useMemory",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMemory/useMemory.demo.tsx")
          return mod
        }),
      },
  
      "useMergedRef": {
        name: "useMergedRef",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMergedRef/useMergedRef.demo.tsx")
          return mod
        }),
      },
  
      "useMount": {
        name: "useMount",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMount/useMount.demo.tsx")
          return mod
        }),
      },
  
      "useMouse": {
        name: "useMouse",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMouse/useMouse.demo.tsx")
          return mod
        }),
      },
  
      "useMutation": {
        name: "useMutation",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMutation/useMutation.demo.tsx")
          return mod
        }),
      },
  
      "useMutationObserver": {
        name: "useMutationObserver",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useMutationObserver/useMutationObserver.demo.tsx")
          return mod
        }),
      },
  
      "useNetwork": {
        name: "useNetwork",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useNetwork/useNetwork.demo.tsx")
          return mod
        }),
      },
  
      "useObject": {
        name: "useObject",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useObject/useObject.demo.tsx")
          return mod
        }),
      },
  
      "useOffsetPagination": {
        name: "useOffsetPagination",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOffsetPagination/useOffsetPagination.demo.tsx")
          return mod
        }),
      },
  
      "useOnce": {
        name: "useOnce",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOnce/useOnce.demo.tsx")
          return mod
        }),
      },
  
      "useOnline": {
        name: "useOnline",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOnline/useOnline.demo.tsx")
          return mod
        }),
      },
  
      "useOperatingSystem": {
        name: "useOperatingSystem",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOperatingSystem/useOperatingSystem.demo.tsx")
          return mod
        }),
      },
  
      "useOptimistic": {
        name: "useOptimistic",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOptimistic/useOptimistic.demo.tsx")
          return mod
        }),
      },
  
      "useOrientation": {
        name: "useOrientation",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOrientation/useOrientation.demo.tsx")
          return mod
        }),
      },
  
      "useOtpCredential": {
        name: "useOtpCredential",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useOtpCredential/useOtpCredential.demo.tsx")
          return mod
        }),
      },
  
      "usePageLeave": {
        name: "usePageLeave",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePageLeave/usePageLeave.demo.tsx")
          return mod
        }),
      },
  
      "usePaint": {
        name: "usePaint",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePaint/usePaint.demo.tsx")
          return mod
        }),
      },
  
      "useParallax": {
        name: "useParallax",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useParallax/useParallax.demo.tsx")
          return mod
        }),
      },
  
      "usePerformanceObserver": {
        name: "usePerformanceObserver",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePerformanceObserver/usePerformanceObserver.demo.tsx")
          return mod
        }),
      },
  
      "usePermission": {
        name: "usePermission",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePermission/usePermission.demo.tsx")
          return mod
        }),
      },
  
      "usePictureInPicture": {
        name: "usePictureInPicture",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePictureInPicture/usePictureInPicture.demo.tsx")
          return mod
        }),
      },
  
      "usePointerLock": {
        name: "usePointerLock",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePointerLock/usePointerLock.demo.tsx")
          return mod
        }),
      },
  
      "usePostMessage": {
        name: "usePostMessage",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePostMessage/usePostMessage.demo.tsx")
          return mod
        }),
      },
  
      "usePreferredColorScheme": {
        name: "usePreferredColorScheme",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePreferredColorScheme/usePreferredColorScheme.demo.tsx")
          return mod
        }),
      },
  
      "usePreferredContrast": {
        name: "usePreferredContrast",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePreferredContrast/usePreferredContrast.demo.tsx")
          return mod
        }),
      },
  
      "usePreferredDark": {
        name: "usePreferredDark",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePreferredDark/usePreferredDark.demo.tsx")
          return mod
        }),
      },
  
      "usePreferredLanguages": {
        name: "usePreferredLanguages",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePreferredLanguages/usePreferredLanguages.demo.tsx")
          return mod
        }),
      },
  
      "usePreferredReducedMotion": {
        name: "usePreferredReducedMotion",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePreferredReducedMotion/usePreferredReducedMotion.demo.tsx")
          return mod
        }),
      },
  
      "usePrevious": {
        name: "usePrevious",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/usePrevious/usePrevious.demo.tsx")
          return mod
        }),
      },
  
      "useProgress": {
        name: "useProgress",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useProgress/useProgress.demo.tsx")
          return mod
        }),
      },
  
      "useQuery": {
        name: "useQuery",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useQuery/useQuery.demo.tsx")
          return mod
        }),
      },
  
      "useQueue": {
        name: "useQueue",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useQueue/useQueue.demo.tsx")
          return mod
        }),
      },
  
      "useRaf": {
        name: "useRaf",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRaf/useRaf.demo.tsx")
          return mod
        }),
      },
  
      "useRafState": {
        name: "useRafState",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRafState/useRafState.demo.tsx")
          return mod
        }),
      },
  
      "useRefState": {
        name: "useRefState",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRefState/useRefState.demo.tsx")
          return mod
        }),
      },
  
      "useRenderCount": {
        name: "useRenderCount",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRenderCount/useRenderCount.demo.tsx")
          return mod
        }),
      },
  
      "useRenderInfo": {
        name: "useRenderInfo",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRenderInfo/useRenderInfo.demo.tsx")
          return mod
        }),
      },
  
      "useRerender": {
        name: "useRerender",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRerender/useRerender.demo.tsx")
          return mod
        }),
      },
  
      "useResizeObserver": {
        name: "useResizeObserver",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useResizeObserver/useResizeObserver.demo.tsx")
          return mod
        }),
      },
  
      "useRightClick": {
        name: "useRightClick",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useRightClick/useRightClick.demo.tsx")
          return mod
        }),
      },
  
      "useScript": {
        name: "useScript",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useScript/useScript.demo.tsx")
          return mod
        }),
      },
  
      "useScroll": {
        name: "useScroll",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useScroll/useScroll.demo.tsx")
          return mod
        }),
      },
  
      "useScrollIntoView": {
        name: "useScrollIntoView",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useScrollIntoView/useScrollIntoView.demo.tsx")
          return mod
        }),
      },
  
      "useScrollTo": {
        name: "useScrollTo",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useScrollTo/useScrollTo.demo.tsx")
          return mod
        }),
      },
  
      "useSessionStorage": {
        name: "useSessionStorage",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useSessionStorage/useSessionStorage.demo.tsx")
          return mod
        }),
      },
  
      "useSet": {
        name: "useSet",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useSet/useSet.demo.tsx")
          return mod
        }),
      },
  
      "useShallowEffect": {
        name: "useShallowEffect",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useShallowEffect/useShallowEffect.demo.tsx")
          return mod
        }),
      },
  
      "useShare": {
        name: "useShare",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useShare/useShare.demo.tsx")
          return mod
        }),
      },
  
      "useSize": {
        name: "useSize",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useSize/useSize.demo.tsx")
          return mod
        }),
      },
  
      "useSpeechRecognition": {
        name: "useSpeechRecognition",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useSpeechRecognition/useSpeechRecognition.demo.tsx")
          return mod
        }),
      },
  
      "useSpeechSynthesis": {
        name: "useSpeechSynthesis",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useSpeechSynthesis/useSpeechSynthesis.demo.tsx")
          return mod
        }),
      },
  
      "useStateHistory": {
        name: "useStateHistory",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useStateHistory/useStateHistory.demo.tsx")
          return mod
        }),
      },
  
      "useStep": {
        name: "useStep",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useStep/useStep.demo.tsx")
          return mod
        }),
      },
  
      "useSticky": {
        name: "useSticky",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useSticky/useSticky.demo.tsx")
          return mod
        }),
      },
  
      "useStopwatch": {
        name: "useStopwatch",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useStopwatch/useStopwatch.demo.tsx")
          return mod
        }),
      },
  
      "useStorage": {
        name: "useStorage",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useStorage/useStorage.demo.tsx")
          return mod
        }),
      },
  
      "useTextDirection": {
        name: "useTextDirection",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useTextDirection/useTextDirection.demo.tsx")
          return mod
        }),
      },
  
      "useTextSelection": {
        name: "useTextSelection",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useTextSelection/useTextSelection.demo.tsx")
          return mod
        }),
      },
  
      "useTextareaAutosize": {
        name: "useTextareaAutosize",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useTextareaAutosize/useTextareaAutosize.demo.tsx")
          return mod
        }),
      },
  
      "useThrottleCallback": {
        name: "useThrottleCallback",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useThrottleCallback/useThrottleCallback.demo.tsx")
          return mod
        }),
      },
  
      "useThrottleEffect": {
        name: "useThrottleEffect",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useThrottleEffect/useThrottleEffect.demo.tsx")
          return mod
        }),
      },
  
      "useThrottleState": {
        name: "useThrottleState",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useThrottleState/useThrottleState.demo.tsx")
          return mod
        }),
      },
  
      "useThrottleValue": {
        name: "useThrottleValue",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useThrottleValue/useThrottleValue.demo.tsx")
          return mod
        }),
      },
  
      "useTime": {
        name: "useTime",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useTime/useTime.demo.tsx")
          return mod
        }),
      },
  
      "useTimeout": {
        name: "useTimeout",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useTimeout/useTimeout.demo.tsx")
          return mod
        }),
      },
  
      "useTimer": {
        name: "useTimer",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useTimer/useTimer.demo.tsx")
          return mod
        }),
      },
  
      "useToggle": {
        name: "useToggle",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useToggle/useToggle.demo.tsx")
          return mod
        }),
      },
  
      "useUnmount": {
        name: "useUnmount",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useUnmount/useUnmount.demo.tsx")
          return mod
        }),
      },
  
      "useUrlSearchParam": {
        name: "useUrlSearchParam",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useUrlSearchParam/useUrlSearchParam.demo.tsx")
          return mod
        }),
      },
  
      "useUrlSearchParams": {
        name: "useUrlSearchParams",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useUrlSearchParams/useUrlSearchParams.demo.tsx")
          return mod
        }),
      },
  
      "useVibrate": {
        name: "useVibrate",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useVibrate/useVibrate.demo.tsx")
          return mod
        }),
      },
  
      "useVirtualKeyboard": {
        name: "useVirtualKeyboard",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useVirtualKeyboard/useVirtualKeyboard.demo.tsx")
          return mod
        }),
      },
  
      "useVisibility": {
        name: "useVisibility",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useVisibility/useVisibility.demo.tsx")
          return mod
        }),
      },
  
      "useWakeLock": {
        name: "useWakeLock",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWakeLock/useWakeLock.demo.tsx")
          return mod
        }),
      },
  
      "useWebSocket": {
        name: "useWebSocket",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWebSocket/useWebSocket.demo.tsx")
          return mod
        }),
      },
  
      "useWindowEvent": {
        name: "useWindowEvent",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWindowEvent/useWindowEvent.demo.tsx")
          return mod
        }),
      },
  
      "useWindowFocus": {
        name: "useWindowFocus",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWindowFocus/useWindowFocus.demo.tsx")
          return mod
        }),
      },
  
      "useWindowScroll": {
        name: "useWindowScroll",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWindowScroll/useWindowScroll.demo.tsx")
          return mod
        }),
      },
  
      "useWindowSize": {
        name: "useWindowSize",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWindowSize/useWindowSize.demo.tsx")
          return mod
        }),
      },
  
      "useWizard": {
        name: "useWizard",
        component: React.lazy(async () => {
          const mod = await import("../../packages/core/src/hooks/useWizard/useWizard.demo.tsx")
          return mod
        }),
      },
  }