import { promises as fs } from 'node:fs';
import path, { resolve } from 'node:path';
import { rimraf } from 'rimraf';

const REPOSITORY_ROOT = resolve(__dirname, '..', '..');

const CORE_ROOT = resolve(REPOSITORY_ROOT, 'core');
const SOURCE_DIR = resolve(CORE_ROOT, 'src/hooks');

const DOC_ROOT = resolve(REPOSITORY_ROOT, 'docs');
const OUTPUT_DIR = resolve(DOC_ROOT, '.source');

async function buildExamplesIndex() {
  await fs.access(SOURCE_DIR);
  console.log('📋 Generating examples/__index__.tsx...');

  const allEntries = await fs.readdir(SOURCE_DIR, { withFileTypes: true });

  const folders = allEntries
    .filter((entry) => !entry.isFile())
    .map((entry) => entry.name)
    .sort();

  const files = await Promise.all(
    Array.from(folders, async (folder) => {
      const allEntries = await fs.readdir(path.join(SOURCE_DIR, folder), { withFileTypes: true });

      const files = allEntries
        .filter((entry) => entry.isFile() && entry.name.endsWith('.demo.tsx'))
        .map((entry) => entry.name)
        .sort();

      const demo = files[0];
      return demo ? { name: folder, demo } : null;
    })
  );

  const withDemos = files.filter((f): f is { name: string; demo: string } => f != null);

  console.log(`   Found ${withDemos.length} demos`);

  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-examples.ts
// Do not edit this file directly.
import * as React from "react"
import dynamic from 'next/dynamic';

export const ExamplesIndex: Record<string, React.ComponentType> = {`;

  for (const file of withDemos) {
    const name = file.name.replace(/\.tsx$/, '');

    index += `
   "${name}": dynamic(() => import("../../core/src/hooks/${file.name}/${file.demo}"), {
      ssr: false,
    }),
  `;
  }

  index += '}';

  const indexPath = path.join(OUTPUT_DIR, 'demo.tsx');
  await rimraf(indexPath);
  await fs.writeFile(indexPath, index);
  console.log(`\n✅ Generated examples/demo.tsx`);
}

buildExamplesIndex().catch(console.error);
