// @ts-nocheck -- skip type checking
import * as docs_11 from "../content/docs/(root)/target.mdx?collection=docs"
import * as docs_10 from "../content/docs/(root)/reactuse-json.mdx?collection=docs"
import * as docs_9 from "../content/docs/(root)/memoization.mdx?collection=docs"
import * as docs_8 from "../content/docs/(root)/installation.mdx?collection=docs"
import * as docs_7 from "../content/docs/(root)/index.mdx?collection=docs"
import * as docs_6 from "../content/docs/(root)/cli.mdx?collection=docs"
import * as docs_5 from "../content/docs/installation/vite.mdx?collection=docs"
import * as docs_4 from "../content/docs/installation/tanstack.mdx?collection=docs"
import * as docs_3 from "../content/docs/installation/tanstack-router.mdx?collection=docs"
import * as docs_2 from "../content/docs/installation/react-router.mdx?collection=docs"
import * as docs_1 from "../content/docs/installation/nextjs.mdx?collection=docs"
import * as docs_0 from "../content/docs/installation/manual.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"installation/manual.mdx","fullPath":"content/docs/installation/manual.mdx"}, data: docs_0 }, { info: {"path":"installation/nextjs.mdx","fullPath":"content/docs/installation/nextjs.mdx"}, data: docs_1 }, { info: {"path":"installation/react-router.mdx","fullPath":"content/docs/installation/react-router.mdx"}, data: docs_2 }, { info: {"path":"installation/tanstack-router.mdx","fullPath":"content/docs/installation/tanstack-router.mdx"}, data: docs_3 }, { info: {"path":"installation/tanstack.mdx","fullPath":"content/docs/installation/tanstack.mdx"}, data: docs_4 }, { info: {"path":"installation/vite.mdx","fullPath":"content/docs/installation/vite.mdx"}, data: docs_5 }, { info: {"path":"(root)/cli.mdx","fullPath":"content/docs/(root)/cli.mdx"}, data: docs_6 }, { info: {"path":"(root)/index.mdx","fullPath":"content/docs/(root)/index.mdx"}, data: docs_7 }, { info: {"path":"(root)/installation.mdx","fullPath":"content/docs/(root)/installation.mdx"}, data: docs_8 }, { info: {"path":"(root)/memoization.mdx","fullPath":"content/docs/(root)/memoization.mdx"}, data: docs_9 }, { info: {"path":"(root)/reactuse-json.mdx","fullPath":"content/docs/(root)/reactuse-json.mdx"}, data: docs_10 }, { info: {"path":"(root)/target.mdx","fullPath":"content/docs/(root)/target.mdx"}, data: docs_11 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"root":true}}])