---
title: Functions
description: A simple catalog of package functions.
---

## List

A quick list of available functions.

- [useActiveElement](/functions/hooks/useActiveElement): Hook for tracking the active element
- [useAsync](/functions/hooks/useAsync): Hook that provides the state of an async callback
- [useAsyncEffect](/functions/hooks/useAsyncEffect): Hook that triggers the effect callback on updates
- [useAudio](/functions/hooks/useAudio): Hook that manages audio playback with sprite support
- [useAutoScroll](/functions/hooks/useAutoScroll): Hook that automatically scrolls a list element to the bottom
- [useBatchedCallback](/functions/hooks/useBatchedCallback): Hook that batches calls and forwards them to a callback
- [useBattery](/functions/hooks/useBattery): Hook for getting information about battery status
- [useBluetooth](/functions/hooks/useBluetooth): Hook for getting information about bluetooth
- [useBoolean](/functions/hooks/useBoolean): Hook provides opportunity to manage boolean state
- [useBreakpoints](/functions/hooks/useBreakpoints): Hook that manages breakpoints
- [useBroadcastChannel](/functions/hooks/useBroadcastChannel): Hook that provides cross-tab/window communication
- [useBrowserLanguage](/functions/hooks/useBrowserLanguage): Hook that returns the current browser language
- [useBrowserLocation](/functions/hooks/useBrowserLocation): Hook that returns reactive browser location state with navigation controls
- [useClickOutside](/functions/hooks/useClickOutside): Hook to handle click events outside the specified target element(s)
- [useClipboard](/functions/hooks/useClipboard): Hook that manages a copy to clipboard
- [useConst](/functions/hooks/useConst): Hook that returns the constant value
- [useContextMenu](/functions/hooks/useContextMenu): Hook that handles custom context menus on desktop and long press on touch devices
- [useControllableState](/functions/hooks/useControllableState): Hook that manages both controlled and uncontrolled state patterns
- [useCookie](/functions/hooks/useCookie): Hook that manages cookie value
- [useCookies](/functions/hooks/useCookies): Hook that manages cookie values
- [useCopy](/functions/hooks/useCopy): Hook that manages copying text with status reset
- [useCounter](/functions/hooks/useCounter): Hook that manages a counter
- [useCssVar](/functions/hooks/useCssVar): Hook that returns the value of a css variable
- [useDebounceCallback](/functions/hooks/useDebounceCallback): Hook that creates a debounced callback
- [useDebounceEffect](/functions/hooks/useDebounceEffect): Hook that runs an effect after a delay when dependencies change
- [useDebounceState](/functions/hooks/useDebounceState): Hook that creates a debounced state
- [useDebounceValue](/functions/hooks/useDebounceValue): Hook that creates a debounced value
- [useDefault](/functions/hooks/useDefault): Hook that returns the default value
- [useDeviceMotion](/functions/hooks/useDeviceMotion): Hook that work with device motion
- [useDeviceOrientation](/functions/hooks/useDeviceOrientation): Hook that provides the current device orientation
- [useDevicePixelRatio](/functions/hooks/useDevicePixelRatio): Hook that returns the device's pixel ratio
- [useDidUpdate](/functions/hooks/useDidUpdate): Hook that triggers the effect callback on updates
- [useDisclosure](/functions/hooks/useDisclosure): Hook that allows you to open and close a modal
- [useDisplayMedia](/functions/hooks/useDisplayMedia): Hook that provides screen sharing functionality
- [useDocumentEvent](/functions/hooks/useDocumentEvent): Hook attaches an event listener to the document object for the specified event
- [useDocumentTitle](/functions/hooks/useDocumentTitle): Hook that manages the document title and allows updating it
- [useDocumentVisibility](/functions/hooks/useDocumentVisibility): Hook that provides the current visibility state of the document
- [useDoubleClick](/functions/hooks/useDoubleClick): Hook that defines the logic when double clicking an element
- [useDropZone](/functions/hooks/useDropZone): Hook that provides drop zone functionality
- [useEvent](/functions/hooks/useEvent): Hook that creates an event and returns a stable reference of it
- [useEventListener](/functions/hooks/useEventListener): Hook that attaches an event listener to the specified target
- [useEventSource](/functions/hooks/useEventSource): Hook that provides a reactive wrapper for event source
- [useEyeDropper](/functions/hooks/useEyeDropper): Hook that gives you access to the eye dropper
- [useFavicon](/functions/hooks/useFavicon): Hook that manages the favicon
- [useField](/functions/hooks/useField): Hook to manage a form field
- [useFileDialog](/functions/hooks/useFileDialog): Hook to handle file input
- [useFileSystemAccess](/functions/hooks/useFileSystemAccess): Hook for reading and writing local files via the File System Access API
- [useFocus](/functions/hooks/useFocus): Hook that allows you to focus on a specific element
- [useFocusTrap](/functions/hooks/useFocusTrap): Hook that traps focus within a given element
- [useFps](/functions/hooks/useFps): Hook that measures frames per second
- [useFul](/functions/hooks/useFul): Hook that can be so useful
- [useFullscreen](/functions/hooks/useFullscreen): Hook to handle fullscreen events
- [useGamepad](/functions/hooks/useGamepad): Hook for getting information about gamepad
- [useGeolocation](/functions/hooks/useGeolocation): Hook that returns the current geolocation
- [useHash](/functions/hooks/useHash): Hook that manages the hash value
- [useHotkeys](/functions/hooks/useHotkeys): Hook that listens for hotkeys
- [useHover](/functions/hooks/useHover): Hook that defines the logic when hovering an element
- [useIdle](/functions/hooks/useIdle): Hook that defines the logic when the user is idle
- [useImage](/functions/hooks/useImage): Hook that load an image in the browser
- [useInfiniteScroll](/functions/hooks/useInfiniteScroll): Hook that defines the logic for infinite scroll
- [useIntersectionObserver](/functions/hooks/useIntersectionObserver): Hook that gives you intersection observer state
- [useInterval](/functions/hooks/useInterval): Hook that makes and interval and returns controlling functions
- [useIsFirstRender](/functions/hooks/useIsFirstRender): Hook that returns true if the component is first render
- [useIsomorphicLayoutEffect](/functions/hooks/useIsomorphicLayoutEffect): Hook conditionally selects either `useLayoutEffect` or `useEffect` based on the environment
- [useKeyboard](/functions/hooks/useKeyboard): Hook that helps to listen for keyboard events
- [useKeyPress](/functions/hooks/useKeyPress): Hook that listens for key press events
- [useKeysPressed](/functions/hooks/useKeysPressed): Hook that tracks all currently pressed keyboard keys and their codes
- [useLastChanged](/functions/hooks/useLastChanged): Hook for records the timestamp of the last change
- [useLatest](/functions/hooks/useLatest): Hook that returns the stable reference of the value
- [useLess](/functions/hooks/useLess): Hook that can be so useless
- [useList](/functions/hooks/useList): Hook that provides state and helper methods to manage a list of items
- [useLocalStorage](/functions/hooks/useLocalStorage): Hook that manages local storage value
- [useLockCallback](/functions/hooks/useLockCallback): Hook that prevents a callback from being executed multiple times simultaneously
- [useLockScroll](/functions/hooks/useLockScroll): Hook that locks scroll on an element or document body
- [useLogger](/functions/hooks/useLogger): Hook for debugging lifecycle
- [useLongPress](/functions/hooks/useLongPress): Hook that defines the logic when long pressing an element
- [useMap](/functions/hooks/useMap): Hook that manages a map structure
- [useMask](/functions/hooks/useMask): Hook to apply an input mask
- [useMeasure](/functions/hooks/useMeasure): Hook to measure the size and position of an element
- [useMediaControls](/functions/hooks/useMediaControls): Hook that provides controls for HTML media elements (audio/video)
- [useMediaQuery](/functions/hooks/useMediaQuery): Hook that manages a media query
- [useMemory](/functions/hooks/useMemory): Hook that gives you current memory usage
- [useMergedRef](/functions/hooks/useMergedRef): Hook that merges multiple refs into a single ref
- [useMount](/functions/hooks/useMount): Hook that executes a callback when the component mounts
- [useMouse](/functions/hooks/useMouse): Hook that manages a mouse position
- [useMutation](/functions/hooks/useMutation): Hook that defines the logic when mutate data
- [useMutationObserver](/functions/hooks/useMutationObserver): Hook that gives you mutation observer state
- [useNetwork](/functions/hooks/useNetwork): Hook to track network status
- [useObject](/functions/hooks/useObject): Hook that provides state and helper methods to manage an object
- [useObjectUrl](/functions/hooks/useObjectUrl): Hook that creates and revokes an object URL for a Blob or MediaSource
- [useOffsetPagination](/functions/hooks/useOffsetPagination): Hook that defines the logic when pagination
- [useOnce](/functions/hooks/useOnce): Hook that runs an effect only once. Please do not use it in production code!
- [useOnline](/functions/hooks/useOnline): Hook that manages if the user is online
- [useOperatingSystem](/functions/hooks/useOperatingSystem): Hook that returns the operating system of the current browser
- [useOptimistic](/functions/hooks/useOptimistic): Hook that allows get optimistic value before its update
- [useOrientation](/functions/hooks/useOrientation): Hook that provides the current screen orientation
- [useOtpCredential](/functions/hooks/useOtpCredential): Hook that creates an otp credential
- [usePageLeave](/functions/hooks/usePageLeave): Hook what calls given function when mouse leaves the page
- [usePaint](/functions/hooks/usePaint): Hook that allows you to draw in a specific area
- [useParallax](/functions/hooks/useParallax): Hook to help create parallax effect
- [usePerformanceObserver](/functions/hooks/usePerformanceObserver): Hook that allows you to observe performance entries
- [usePermission](/functions/hooks/usePermission): Hook that gives you the state of permission
- [usePictureInPicture](/functions/hooks/usePictureInPicture): Hook that provides Picture-in-Picture functionality for video elements
- [usePointerLock](/functions/hooks/usePointerLock): Hook that provides reactive pointer lock
- [usePostMessage](/functions/hooks/usePostMessage): Hook that allows you to receive messages from other origins
- [usePreferredColorScheme](/functions/hooks/usePreferredColorScheme): Hook that returns user preferred color scheme
- [usePreferredContrast](/functions/hooks/usePreferredContrast): Hook that returns the contrast preference
- [usePreferredDark](/functions/hooks/usePreferredDark): Hook that returns if the user prefers dark mode
- [usePreferredLanguages](/functions/hooks/usePreferredLanguages): that returns a browser preferred languages from navigator
- [usePreferredReducedMotion](/functions/hooks/usePreferredReducedMotion): Hook that returns the reduced motion preference
- [usePrevious](/functions/hooks/usePrevious): Hook that returns the previous value
- [useProgress](/functions/hooks/useProgress): Hook that creates a lightweight progress bar
- [useQuery](/functions/hooks/useQuery): Hook that defines the logic when query data
- [useQueue](/functions/hooks/useQueue): Hook that manages a queue
- [useRaf](/functions/hooks/useRaf): Hook that defines the logic for raf callback
- [useRafState](/functions/hooks/useRafState): Hook that returns the value and a function to set the value
- [useRefState](/functions/hooks/useRefState): Hook that returns the state reference of the value
- [useRenderCount](/functions/hooks/useRenderCount): Hook returns count component render times
- [useRenderInfo](/functions/hooks/useRenderInfo): Hook for getting information about component rerender
- [useRerender](/functions/hooks/useRerender): Hook that defines the logic to force rerender a component
- [useResizeObserver](/functions/hooks/useResizeObserver): Hook that gives you resize observer state
- [useScript](/functions/hooks/useScript): Hook that manages a script with onLoad, onError, and removeOnUnmount functionalities
- [useScroll](/functions/hooks/useScroll): Hook that allows you to control scroll a element
- [useScrollIntoView](/functions/hooks/useScrollIntoView): Hook that provides functionality to scroll an element into view
- [useScrollTo](/functions/hooks/useScrollTo): Hook for scrolling to a specific element
- [useSessionStorage](/functions/hooks/useSessionStorage): Hook that manages session storage value
- [useSet](/functions/hooks/useSet): Hook that manages a set structure
- [useShallowEffect](/functions/hooks/useShallowEffect): Hook that executes an effect only when dependencies change shallowly or deeply
- [useShare](/functions/hooks/useShare): Hook that utilizes the share api